export const url = {
  getUserProfileData: '/index.php/profile/info',
  GetAllUsers: '/index.php/admin/GetAllUsers/',
  verifyLogin: '/index.php/VerifyLogin',
  createNodeUrl: '/index.php/ObjectController/CreateNode',
  getTableData: '/index.php/ObjectController/GetTableData',
  addValueObject: '/index.php/ObjectController/AddValueObject/true',
  getInheritParamsForTableUrl:
    '/index.php/UIController/GetInheritParamsForTable',
  addDopParamsUrl: '/index.php/Cache/cache_add_table',
  calcforObjecttoTable: '/index.php/ObjectController/CalcforObjecttoTable',
  calcContextValuesBTN: '/index.php/CalcsController/CalcContextValuesBTN',
  deleteNodeURL: '/index.php/ObjectController/DeleteNode',
  getEnumsData: '/index.php/ObjectController/GetEnumsData',
  delObjMassUrl: '/index.php/ObjectController/DeleteObjMass',
  addValueObjTrue: '/index.php/ObjectController/AddValueObject/true',
  getDataColumnTableForInterface:
    '/index.php/ObjectController/GetDataColumnTableForInterface',
  getReports: '/index.php/UISettingsController/GetReports',
  getreportFormodule: '/index.php/RepCalcController/GetReportForModule',
  GetExcelforCalc: '/index.php/RepCalcController/GetExcelforCalc',
  BuildWindowForm: '/index.php/UIController/BuildWindowForm',
  calcsController: '/index.php/CalcsController/CalcContextValuesBTN',
  learnController: '/index.php/learncontroller/getdata',
  updateDataEndpoint: '/index.php/learncontroller/includecourses',
  lockCoursesEndpoint: '/index.php/learncontroller/excludecourses',
  getUsersStatistics: '/index.php/Learncontroller/getUsersStatistics',
  getUsersStatisticsBestTry:
    '/index.php/Learncontroller/getUsersStatisticsBestTry',
  getDetailedUserStatisctics: '/index.php/Learncontroller/getUserStatistic',
};
